### PR TITLE
Option to read (spatially varying) KHTH from file

### PR DESCRIPTION
**Pull request by NoraLoose**
This adds the option to read a spatially varying GM interface height diffusivity (KHTH) from a netcdf file.

### CODE REVIEW

**Comment by NoraLoose** [comment]
@gustavo-marques, I solved the previous problem. There was nothing wrong with the code, I just forgot to set `THICKNESSDIFFUSE = True`. I updated the comment above.

But I noticed another problem. Here is what I give the model versus what the diagnostic `KHTH_t` gives me:

KHTH_t


Is the spurious "tile structure" on the right implied by `MOM_read_data`?

**Comment by NoraLoose** [comment]
Alistair (@adcroft), maybe you have seen the problem described in the previous comment before?

**Comment by adcroft** [comment]
That looks like a classic missing halo-update. I don't think `MOM_read_data()` fills the halo. You are interpolating to the edge of the compute domain which is using a halo value of zero (if initialized) rather than the correct value from the neighbouring processor. Try adding a `pass_var()` after reading the data.

**Comment by NoraLoose** [comment]
Thanks @adcroft - this solved the problem!

**Comment by NoraLoose** [comment]
@gustavo-marques @adcroft is this PR of interest for the MOM6 code (upstream)? 

If so, it will take some work to merge it because I started from the dev/cpt branch, which has significantly diverged from the upstream master branch. 

I successfully tested the new code for the NeverWorld2 setup, but I have to admit I have never compiled or run MOM6 in a more complex configuration. Gustavo, do you have a working (and up to date) setup on Cheyenne that we could use for testing?

**Comment by gustavo-marques** [comment]
Hi @NoraLoose: yes, I think we should merge this PR to the main branch eventually. I can take care of that and if I get conflicts related to the changes in this PR I will reach out to you. Thanks!

**Comment by NoraLoose** [comment]
@gustavo-marques have you tried merging this yet? If not, I will try and reach out to you if I get stuck. Thanks!

**Comment by gustavo-marques** [comment]
No, I have not.

**Comment by NoraLoose** [comment]
Closing this PR because I have [opened it at NOAA/GFDL](https://github.com/NOAA-GFDL/MOM6/pull/236).

**Pull request closed without merging**
