### PR TITLE
Thickness-multiplied 3D momentum budget terms

### PR DESCRIPTION
**Pull request by hmkhatri**
I have added 3D diagnostics (layer thickness x momentum budget terms), which are required for analysis in the thickness-weighted framework.

### CODE REVIEW

**Comment by adcroft** [comment]
Did this PR go to GFDL as well, or just here?

**Comment by hmkhatri** [comment]
@adcroft This PR is only here. I have not put any PR for these diagnostics to the GFDL branch.

**Comment by adcroft** [comment]
OK - just needed to know for purposes of review

**Comment by gustavo-marques** [comment]
@hmkhatri, can you please close this PR and create a new one into dev/gfdl? Once this is merged into dev/gfdl we can update dev/cpt.

**Comment by hmkhatri** [comment]
@gustavo-marques Sure. I will put a new PR to MOM6 dev/gfdl branch.

**Pull request closed without merging**
